USE master;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'OCR_DB')
BEGIN
    DROP DATABASE OCR_DB;
END
GO
CREATE DATABASE OCR_DB;
GO

USE OCR_DB;
GO

CREATE TABLE DETECTED_NUMBER (
    Id INT IDENTITY(1,1) NOT NULL,
    Recognized_Text VARCHAR(20),
    Enhanced_File_Path TEXT,
    CONSTRAINT PK_DETECTED_NUMBER_ID PRIMARY KEY (Id)
);
GO 
